// Central registry of the DOM elements the app touches, resolved once at load.

function getEl<T extends Element>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Element #${id} not found`);
  return el as unknown as T;
}

export const els = {
  searchForm: getEl<HTMLFormElement>("search-form"),
  searchInput: getEl<HTMLInputElement>("search-input"),
  authAvatarButton: getEl<HTMLAnchorElement>("auth-avatar-button"),
  authAvatarInitials: getEl<HTMLElement>("auth-avatar-initials"),
  accountView: getEl<HTMLElement>("account-view"),
  accountGuestLogin: getEl<HTMLElement>("account-guest-login"),
  accountGuestRegister: getEl<HTMLElement>("account-guest-register"),
  accountSignedIn: getEl<HTMLElement>("account-signed-in"),
  accountEditUsername: getEl<HTMLElement>("account-edit-username"),
  accountEditEmail: getEl<HTMLElement>("account-edit-email"),
  accountUsernameDisplay: getEl<HTMLElement>("account-username-display"),
  accountUnverifiedPrompt: getEl<HTMLElement>("account-unverified-prompt"),
  welcomeVerifyView: getEl<HTMLElement>("welcome-verify-view"),
  welcomeVerifyEmail: getEl<HTMLElement>("welcome-verify-email"),
  welcomeResendButton: getEl<HTMLButtonElement>("welcome-resend-button"),
  toastPopup: getEl<HTMLElement>("toast-popup"),
  toastPopupMessage: getEl<HTMLElement>("toast-popup-message"),
  toastPopupDismiss: getEl<HTMLButtonElement>("toast-popup-dismiss"),
  showRegisterButton: getEl<HTMLButtonElement>("show-register"),
  showLoginButton: getEl<HTMLButtonElement>("show-login"),
  showForgotPasswordButton: getEl<HTMLButtonElement>("show-forgot-password"),
  loginForm: getEl<HTMLFormElement>("login-form"),
  registerForm: getEl<HTMLFormElement>("register-form"),
  forgotPasswordForm: getEl<HTMLFormElement>("forgot-password-form"),
  loginIdentifier: getEl<HTMLInputElement>("login-identifier"),
  loginPassword: getEl<HTMLInputElement>("login-password"),
  forgotPasswordEmail: getEl<HTMLInputElement>("forgot-password-email"),
  forgotPasswordSubmit: getEl<HTMLButtonElement>("forgot-password-submit"),
  forgotPasswordCancel: getEl<HTMLButtonElement>("forgot-password-cancel"),
  registerUsername: getEl<HTMLInputElement>("register-username"),
  registerEmail: getEl<HTMLInputElement>("register-email"),
  registerPassword: getEl<HTMLInputElement>("register-password"),
  registerPasswordConfirm: getEl<HTMLInputElement>("register-password-confirm"),
  registerPasswordMatch: getEl<HTMLElement>("register-password-match"),
  loginSubmit: getEl<HTMLButtonElement>("login-submit"),
  registerSubmit: getEl<HTMLButtonElement>("register-submit"),
  accountUsernameForm: getEl<HTMLFormElement>("account-username-form"),
  accountUsernameWarning: getEl<HTMLElement>("account-username-warning"),
  accountNewUsername: getEl<HTMLInputElement>("account-new-username"),
  accountUsernamePassword: getEl<HTMLInputElement>("account-username-password"),
  accountUsernameSubmit: getEl<HTMLButtonElement>("account-username-submit"),
  accountEmailForm: getEl<HTMLFormElement>("account-email-form"),
  accountEmailWarning: getEl<HTMLElement>("account-email-warning"),
  accountNewEmail: getEl<HTMLInputElement>("account-new-email"),
  accountEmailPassword: getEl<HTMLInputElement>("account-email-password"),
  accountEmailSubmit: getEl<HTMLButtonElement>("account-email-submit"),
  accountChangePassword: getEl<HTMLButtonElement>("account-change-password"),
  logoutButton: getEl<HTMLButtonElement>("logout-button"),
  verifyEmailView: getEl<HTMLElement>("verify-email-view"),
  verifyEmailStatus: getEl<HTMLElement>("verify-email-status"),
  resetPasswordView: getEl<HTMLElement>("reset-password-view"),
  resetPasswordForm: getEl<HTMLFormElement>("reset-password-form"),
  resetPassword: getEl<HTMLInputElement>("reset-password"),
  resetPasswordConfirm: getEl<HTMLInputElement>("reset-password-confirm"),
  resetPasswordMatch: getEl<HTMLElement>("reset-password-match"),
  resetPasswordStatus: getEl<HTMLElement>("reset-password-status"),
  resetPasswordSubmit: getEl<HTMLButtonElement>("reset-password-submit"),
  message: getEl<HTMLElement>("message"),
  welcome: getEl<HTMLElement>("welcome"),
  player: getEl<HTMLElement>("player"),
  playerName: getEl<HTMLElement>("player-name"),
  playerTag: getEl<HTMLElement>("player-tag"),
  scoreLabel: getEl<HTMLElement>("score-label"),
  currentScore: getEl<HTMLElement>("current-score"),
  currentChange: getEl<HTMLElement>("current-change"),
  scoreContext: getEl<HTMLElement>("score-context"),
  refreshButton: getEl<HTMLButtonElement>("refresh-button"),
  snapshotCount: getEl<HTMLElement>("snapshot-count"),
  lastUpdated: getEl<HTMLElement>("last-updated"),
  rangeFilters: getEl<HTMLElement>("range-filters"),
  chartArea: getEl<HTMLElement>("chart-area"),
  chartSvg: getEl<SVGSVGElement>("chart-svg"),
  chartTooltip: getEl<HTMLElement>("chart-tooltip"),
  historyEmpty: getEl<HTMLElement>("history-empty"),
};
